openapi: "3.0.0"

info:
  title: "autoML API v2"
  description: "API that accepts a json file and returns a model result."
  version: "1.5"
  
servers:
  - url: https://tp-faa-v001.herokuapp.com
    description: heroku app server

paths:
  /extractpackages:
  
    post:
      description: "feature input"

      requestBody:
        description: "Json with single field containing text to extract entities from"
        required: true
        content:
          application/json: {}
          text/plain:
              schema:
                type: string

      responses:
        '200':
          description: "Returns names & indexs of packages in the provided text"
          content: 
           text/plain:
              schema:
                type: string
